CREATE TABLE PACIENTE(
    ID UUID PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,

    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15),

    LOGRADOURO VARCHAR(250),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    UF CHAR(2),
    CEP VARCHAR(8),

    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP
);

CREATE UNIQUE INDEX UK_PACIENTE_CPF ON PACIENTE (CPF);
CREATE UNIQUE INDEX UK_PACIENTE_EMAIL ON PACIENTE (EMAIL);
CREATE INDEX IDX_PACIENTE_NOME ON PACIENTE (NOME);
